name: Sync Silver Drift Monitoring to Databricks

on:
  push:
    paths:
      - 'monitoring/silver_drift_monitoring.py'
      - 'monitoring/silver_drift_monitoring.ipynb'

jobs:
  sync-to-databricks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks configure --token <<EOF
          $DATABRICKS_HOST
          $DATABRICKS_TOKEN
          EOF


      - name: Delete old silver_drift_monitoring.py in Databricks Workspace
        run: |
          databricks workspace delete /Workspace/Users/diego.mayorgacapera@gmail.com/.bundle/BI_Market_Visibility/dev/files/monitoring/silver_drift_monitoring.py --recursive --force

      - name: Upload silver_drift_monitoring.py to Databricks Workspace
        run: |
          databricks workspace import monitoring/silver_drift_monitoring.py \
            /Workspace/Users/diego.mayorgacapera@gmail.com/.bundle/BI_Market_Visibility/dev/files/monitoring/silver_drift_monitoring.py \
            --overwrite

      - name: Delete old silver_drift_monitoring.ipynb in Databricks Workspace
        run: |
          databricks workspace delete /Workspace/Users/diego.mayorgacapera@gmail.com/.bundle/BI_Market_Visibility/dev/files/monitoring/silver_drift_monitoring.ipynb --recursive --force

      - name: Upload silver_drift_monitoring.ipynb to Databricks Workspace
        run: |
          databricks workspace import monitoring/silver_drift_monitoring.ipynb \
            /Workspace/Users/diego.mayorgacapera@gmail.com/.bundle/BI_Market_Visibility/dev/files/monitoring/silver_drift_monitoring.ipynb \
            --format JUPYTER --overwrite
